// Generated by CoffeeScript 1.4.0

/* Configuration file - Set your Readabiliy/Twitter variables here
*/


(function() {

  exports.TW_CONSUMER_KEY = process.env.TW_CONSUMER_KEY || '';

  exports.TW_CONSUMER_SECRET = process.env.TW_CONSUMER_SECRET || '';

  exports.TW_USERNAME = process.env.TW_USERNAME || '';

  exports.RDB_CONSUMER_KEY = process.env.RDB_CONSUMER_KEY || '';

  exports.RDB_CONSUMER_SECRET = process.env.RDB_CONSUMER_SECRET || '';

  exports.REDIS_PORT = process.env.REDIS_PORT || '6379';

  exports.REDIS_HOSTNAME = process.env.REDIS_HOSTNAME || 'localhost';

  exports.HOSTNAME = process.env.HOSTNAME || 'localhost';

  exports.PORT = process.env.PORT || '3000';

  /* Only needed for test suite
  */


  exports.TW_PASSWORD = process.env.TW_PASSWORD || '';

}).call(this);
