// Generated by CoffeeScript 1.6.3
(function() {
  var app, cfg, express;

  express = require('express');

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express.bodyParser());

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  app.use(express["static"](__dirname + '/static'));

  /* Controllers*/


  /* Routes*/


  app.get('/', function(req, res) {
    return res.render('index', {});
  });

  app.get('/status', function(req, res) {});

  /* Start the App*/


  app.listen("" + cfg.PORT);

}).call(this);
