// Generated by CoffeeScript 1.4.0

/* Tests for Config /cfg
*/


(function() {
  var cfg, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  describe('Server Config', function() {
    it('Should have a hostname', function() {
      var tmp;
      tmp = cfg.HOSTNAME;
      return tmp.should.not.eql('');
    });
    return it('Should have a port number', function() {
      var tmp;
      tmp = cfg.PORT;
      return tmp.should.not.eql('');
    });
  });

}).call(this);
