// Generated by CoffeeScript 1.4.0

/* Client-side tests via Zombie (headless browser) /node_modules/zombie
*/


(function() {
  var Browser, browser, cfg, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Browser = require('zombie');

  browser = new Browser;

  describe('Zombie is eating braiiiiinssssss', function() {});

}).call(this);
